# Generated by Django 4.1.7 on 2024-01-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actor', models.CharField(max_length=100)),
                ('Director', models.CharField(max_length=100)),
            ],
        ),
    ]
